version: "3"

services:
    keycloak:
        image: quay.io/keycloak/keycloak:21.1
        command: start-dev
        ports:
            - 8080:8080
        environment:
            KC_DB: postgres
            KC_DB_URL_HOST: db
            KC_DB_URL_DATABASE: keycloak
            KC_DB_PASSWORD: root
            KC_DB_USERNAME: root
            KC_DB_SCHEMA: public
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:16.2
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d keycloak -U root -h localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
